In [2]:
import pandas as pd
from collections import Counter
import itertools
import numpy as np
from scipy import stats

In [25]:
working_dir = "C:\\Users\\Joshua\\Documents\\GitSources\\TabletopGames_StirFry18\\SF18Experiments\\100RUNS"
action_taken_dataframe = pd.read_csv(working_dir+'\\ACTION_TAKEN.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Joshua\\Documents\\GitSources\\TabletopGames_StirFry18\\SF18Experiments\\100RUNS\\ACTION_TAKEN.csv'

In [ ]:
# Create a simplified dataframe with only the columns we want
simplified_df = action_taken_dataframe[['GameSeed', 
                                        'FavoredCards(Discarded card)', 
                                        'FavoredCards(Favored Cards)']]

# Remove rows where both card columns have no value
# This handles various forms of "no value" (None, NaN, empty string)
simplified_df = simplified_df.dropna(subset=['FavoredCards(Discarded card)', 
                                            'FavoredCards(Favored Cards)'], 
                                    how='all')

# Also remove rows where both columns are empty strings
mask = ~((simplified_df['FavoredCards(Discarded card)'].fillna('') == '') & 
         (simplified_df['FavoredCards(Favored Cards)'].fillna('') == ''))
simplified_df = simplified_df[mask]

# Display the first few rows of the simplified dataframe
simplified_df.head()

In [5]:
# Create a simplified dataframe with only the columns we want
simplified_df = action_taken_dataframe[['GameSeed', 
                                        'FavoredCards(Discarded card)', 
                                        'FavoredCards(Favored Cards)']]

# Remove rows where both card columns have no value
simplified_df = simplified_df.dropna(subset=['FavoredCards(Discarded card)', 
                                            'FavoredCards(Favored Cards)'], 
                                    how='all')

# Also remove rows where both columns are empty strings
mask = ~((simplified_df['FavoredCards(Discarded card)'].fillna('') == '') & 
         (simplified_df['FavoredCards(Favored Cards)'].fillna('') == ''))
simplified_df = simplified_df[mask]

# Rename the columns
simplified_df = simplified_df.rename(columns={
    'FavoredCards(Discarded card)': 'Discarded card',
    'FavoredCards(Favored Cards)': 'Favored card'
})

# Display the first few rows of the simplified dataframe
simplified_df.head()

,GameSeed,Discarded card,Favored card
6,2034470281,GREEN_ONION,MUSHROOMS-PORK-SOY_SAUCE-
11,2034470281,CHICKEN,GREEN_ONION-MUSHROOMS-MUSHROOMS-NOODLES-NOODLES-
12,2034470281,NOODLES,GINGER-GREEN_ONION-GREEN_ONION-MUSHROOMS-MUSHR...
30,2034470281,SOY_SAUCE,MUSHROOMS-NOODLES-NOODLES-SHRIMP-
34,2034470281,GREEN_ONION,GINGER-GINGER-MUSHROOMS-NOODLES-SOY_SAUCE-

In [6]:
pd.isnull(simplified_df).values.sum()

0

In [7]:
# Function to clean up the favored cards string and remove duplicates
def clean_and_deduplicate_favored_cards(card_string):
    if pd.isna(card_string) or card_string == '':
        return ''
    
    # Remove trailing dash if present
    if card_string.endswith('-'):
        card_string = card_string[:-1]
    
    # Split by dash, remove duplicates while preserving order, and rejoin
    items = card_string.split('-')
    
    # Remove duplicates while preserving order
    unique_items = []
    for item in items:
        if item and item not in unique_items:  # Skip empty strings and duplicates
            unique_items.append(item)
    
    # Rejoin the unique items
    return '-'.join(unique_items)

# Apply the cleaning and deduplication function
simplified_df['Favored card'] = simplified_df['Favored card'].apply(clean_and_deduplicate_favored_cards)

# If you want to also create a list version of the column
simplified_df['Favored card list'] = simplified_df['Favored card'].apply(
    lambda x: x.split('-') if x else []
)

# Display the first few rows of the cleaned dataframe
simplified_df.head()

,GameSeed,Discarded card,Favored card,Favored card list
6,2034470281,GREEN_ONION,MUSHROOMS-PORK-SOY_SAUCE,"[MUSHROOMS, PORK, SOY_SAUCE]"
11,2034470281,CHICKEN,GREEN_ONION-MUSHROOMS-NOODLES,"[GREEN_ONION, MUSHROOMS, NOODLES]"
12,2034470281,NOODLES,GINGER-GREEN_ONION-MUSHROOMS-NOODLES,"[GINGER, GREEN_ONION, MUSHROOMS, NOODLES]"
30,2034470281,SOY_SAUCE,MUSHROOMS-NOODLES-SHRIMP,"[MUSHROOMS, NOODLES, SHRIMP]"
34,2034470281,GREEN_ONION,GINGER-MUSHROOMS-NOODLES-SOY_SAUCE,"[GINGER, MUSHROOMS, NOODLES, SOY_SAUCE]"

In [8]:
# First, make sure we have the 'Favored card list' column
if 'Favored card list' not in simplified_df.columns:
    # Create the 'Favored card list' column from the 'Favored card' column
    simplified_df['Favored card list'] = simplified_df['Favored card'].apply(
        lambda x: [] if pd.isna(x) or x == '' else list(dict.fromkeys(x.rstrip('-').split('-')))
    )

# Now drop the 'Favored card' column
simplified_df = simplified_df.drop(columns=['Favored card'])

# Rename 'Favored card list' to 'Favored card' if you want to keep the original name
simplified_df = simplified_df.rename(columns={'Favored card list': 'Favored card'})

# Display the first few rows of the modified dataframe
print("Columns after modification:", simplified_df.columns.tolist())
simplified_df.head()

Columns after modification: ['GameSeed', 'Discarded card', 'Favored card']

      GameSeed Discarded card                               Favored card
6   2034470281    GREEN_ONION               [MUSHROOMS, PORK, SOY_SAUCE]
11  2034470281        CHICKEN          [GREEN_ONION, MUSHROOMS, NOODLES]
12  2034470281        NOODLES  [GINGER, GREEN_ONION, MUSHROOMS, NOODLES]
30  2034470281      SOY_SAUCE               [MUSHROOMS, NOODLES, SHRIMP]
34  2034470281    GREEN_ONION    [GINGER, MUSHROOMS, NOODLES, SOY_SAUCE]

In [9]:
# Create a list to store all pairs
all_pairs = []

# Iterate through each row in the simplified dataframe
for _, row in simplified_df.iterrows():
    discarded = row['Discarded card']
    favored_list = row['Favored card']  # This should be a list now
    
    # Skip if discarded is empty or favored_list is empty
    if pd.isna(discarded) or discarded == '' or not favored_list:
        continue
    
    # Create pairs between discarded card and each element in favored list
    for favored in favored_list:
        if favored:  # Skip empty strings
            all_pairs.append((discarded, favored))

# Count the occurrences of each pair
pair_counts = Counter(all_pairs)

# Create a new dataframe from the pair counts
pairs_df = pd.DataFrame([
    {'Discarded': pair[0], 'Favored': pair[1], 'Count': count, 'Value': -1 * count}
    for pair, count in pair_counts.items()
])

# Sort by count in descending order
pairs_df = pairs_df.sort_values('Count', ascending=False).reset_index(drop=True)

# Display the total number of unique pairs and the first few rows
print(f"Total unique pairs: {len(pairs_df)}")
pairs_df.head(10)

Total unique pairs: 61

   Discarded      Favored  Count  Value
0    NOODLES    SOY_SAUCE    410   -410
1    NOODLES      NOODLES    393   -393
2    NOODLES    MUSHROOMS    374   -374
3     SHRIMP      NOODLES    337   -337
4     SHRIMP    MUSHROOMS    311   -311
5  SOY_SAUCE    MUSHROOMS    305   -305
6     SHRIMP    SOY_SAUCE    294   -294
7    NOODLES  GREEN_ONION    293   -293
8       PORK      NOODLES    287   -287
9    NOODLES       GINGER    284   -284

In [10]:
# Function to create a canonical representation of a pair (alphabetical order)
def canonical_pair(item1, item2):
    return tuple(sorted([item1, item2]))

# Function to calculate Wilson score interval for a proportion
def wilson_score_interval(p, n, z=1.96):  # z=1.96 for 95% confidence
    denominator = 1 + z**2/n
    center = (p + z**2/(2*n)) / denominator
    spread = z * np.sqrt(p * (1 - p) / n + z**2 / (4 * n**2)) / denominator
    return center, spread

# First, create the pairs between discarded and favored
discarded_favored_pairs = []

# Iterate through each row in the simplified dataframe
for _, row in simplified_df.iterrows():
    discarded = row['Discarded card']
    favored_list = row['Favored card']  # This should be a list now
    
    # Skip if discarded is empty or favored_list is empty
    if pd.isna(discarded) or discarded == '' or not favored_list:
        continue
    
    # Create pairs between discarded card and each element in favored list
    for favored in favored_list:
        if favored:  # Skip empty strings
            # Store pairs in canonical form (alphabetically sorted)
            discarded_favored_pairs.append(canonical_pair(discarded, favored))

# Count the occurrences of each discarded-favored pair
discarded_favored_counts = Counter(discarded_favored_pairs)

# Now, create pairs WITHIN the favored card lists
within_favored_pairs = []

# Iterate through each row in the simplified dataframe
for _, row in simplified_df.iterrows():
    favored_list = row['Favored card']  # This should be a list now
    
    # Skip if favored_list is empty or has only one element
    if not favored_list or len(favored_list) < 2:
        continue
    
    # Create all possible pairs within the favored list
    for item1, item2 in itertools.combinations(favored_list, 2):
        if item1 and item2:  # Skip empty strings
            # Store pairs in canonical form (alphabetically sorted)
            within_favored_pairs.append(canonical_pair(item1, item2))

# Count the occurrences of each within-favored pair
within_favored_counts = Counter(within_favored_pairs)

# Create a combined dictionary of all pairs and their values
all_pair_values = {}

# Add discarded-favored pairs with value -1 per occurrence
for pair, count in discarded_favored_counts.items():
    all_pair_values[pair] = {
        'Count_Negative': count,  # Count of -1 values
        'Count_Zero': 0,          # Count of 0 values
        'Total_Count': count,
        'Value': -1 * count
    }

# Add within-favored pairs with value 0 per occurrence
for pair, count in within_favored_counts.items():
    if pair in all_pair_values:
        all_pair_values[pair]['Count_Zero'] = count
        all_pair_values[pair]['Total_Count'] += count
        # Value remains unchanged since adding 0
    else:
        all_pair_values[pair] = {
            'Count_Negative': 0,
            'Count_Zero': count,
            'Total_Count': count,
            'Value': 0
        }

# Create a new dataframe from all pairs
pairs_df = pd.DataFrame([
    {
        'Ingredient1': pair[0], 
        'Ingredient2': pair[1], 
        'Count': data['Total_Count'], 
        'Value': data['Value'],
        'Count_Negative': data['Count_Negative'],
        'Count_Zero': data['Count_Zero']
    }
    for pair, data in all_pair_values.items()
])

# Add the Average column (Value/Count)
pairs_df['Average'] = pairs_df['Value'] / pairs_df['Count']

# Calculate proportion of negative values (p)
pairs_df['Proportion_Negative'] = pairs_df['Count_Negative'] / pairs_df['Count']

# Calculate Wilson score center and error
wilson_results = pairs_df.apply(
    lambda row: wilson_score_interval(row['Proportion_Negative'], row['Count']),
    axis=1
)

# Add Wilson score error column
pairs_df['Wilson_Center'] = [-result[0] for result in wilson_results]  # Negate because our values are negative
pairs_df['Wilson_Error'] = [result[1] for result in wilson_results]

# Sort by count in descending order
pairs_df = pairs_df.sort_values('Count', ascending=False).reset_index(drop=True)

# Display the first few rows with the most important columns
pairs_df[['Ingredient1', 'Ingredient2', 'Count', 'Average', 'Wilson_Center', 'Wilson_Error']].head(10)

   Ingredient1 Ingredient2  Count   Average  Wilson_Center  Wilson_Error
0      NOODLES   SOY_SAUCE   1818 -0.378988      -0.379243      0.022279
1    MUSHROOMS     NOODLES   1780 -0.336517      -0.336869      0.021931
2    MUSHROOMS   SOY_SAUCE   1662 -0.332130      -0.332517      0.022621
3       GINGER     NOODLES   1344 -0.280506      -0.281132      0.023992
4       GINGER   SOY_SAUCE   1318 -0.298179      -0.298766      0.024668
5       GINGER   MUSHROOMS   1297 -0.272938      -0.273608      0.024217
6  GREEN_ONION     NOODLES   1286 -0.279160      -0.279818      0.024490
7  GREEN_ONION   SOY_SAUCE   1232 -0.286526      -0.287190      0.025217
8  GREEN_ONION   MUSHROOMS   1215 -0.263374      -0.264120      0.024739
9      CHICKEN     NOODLES   1001 -0.450549      -0.450739      0.030765

In [11]:
pairs_df

,Ingredient1,Ingredient2,Count,Value,Count_Negative,Count_Zero,Average,Proportion_Negative,Wilson_Center,Wilson_Error
0,NOODLES,SOY_SAUCE,1818,-689,689,1129,-0.378988,0.378988,-0.379243,0.022279
1,MUSHROOMS,NOODLES,1780,-599,599,1181,-0.336517,0.336517,-0.336869,0.021931
2,MUSHROOMS,SOY_SAUCE,1662,-552,552,1110,-0.332130,0.332130,-0.332517,0.022621
3,GINGER,NOODLES,1344,-377,377,967,-0.280506,0.280506,-0.281132,0.023992
4,GINGER,SOY_SAUCE,1318,-393,393,925,-0.298179,0.298179,-0.298766,0.024668
5,GINGER,MUSHROOMS,1297,-354,354,943,-0.272938,0.272938,-0.273608,0.024217
6,GREEN_ONION,NOODLES,1286,-359,359,927,-0.279160,0.279160,-0.279818,0.024490
7,GREEN_ONION,SOY_SAUCE,1232,-353,353,879,-0.286526,0.286526,-0.287190,0.025217
8,GREEN_ONION,MUSHROOMS,1215,-320,320,895,-0.263374,0.263374,-0.264120,0.024739
9,CHICKEN,NOODLES,1001,-451,451,550,-0.450549,0.450549,-0.450739,0.030765
10,GINGER,GREEN_ONION,940,-201,201,739,-0.213830,0.213830,-0.214995,0.026184
11,NOODLES,PORK,929,-453,453,476,-0.487621,0.487621,-0.487672,0.032077
12,NOODLES,SHRIMP,890,-495,495,395,-0.556180,0.556180,-0.555938,0.032572
13,CHICKEN,MUSHROOMS,882,-351,351,531,-0.397959,0.397959,-0.398402,0.032237
14,CHICKEN,SOY_SAUCE,877,-367,367,510,-0.418472,0.418472,-0.418828,0.032580
15,MUSHROOMS,SHRIMP,844,-410,410,434,-0.485782,0.485782,-0.485846,0.033643
16,MUSHROOMS,PORK,806,-365,365,441,-0.452854,0.452854,-0.453077,0.034284
17,SHRIMP,SOY_SAUCE,791,-413,413,378,-0.522124,0.522124,-0.522017,0.034727
18,PORK,SOY_SAUCE,774,-360,360,414,-0.465116,0.465116,-0.465289,0.035053
19,CHICKEN,GINGER,683,-231,231,452,-0.338214,0.338214,-0.339119,0.035394
20,CHICKEN,GREEN_ONION,660,-241,241,419,-0.365152,0.365152,-0.365932,0.036635
21,GINGER,PORK,637,-261,261,376,-0.409733,0.409733,-0.410274,0.038080
22,GINGER,SHRIMP,615,-301,301,314,-0.489431,0.489431,-0.489497,0.039386
23,GREEN_ONION,PORK,605,-225,225,380,-0.371901,0.371901,-0.372709,0.038400
24,GREEN_ONION,SHRIMP,592,-295,295,297,-0.498311,0.498311,-0.498322,0.040147
25,CHICKEN,PORK,421,-211,211,210,-0.501188,0.501188,-0.501177,0.047546
26,CHICKEN,SHRIMP,419,-265,265,154,-0.632458,0.632458,-0.631255,0.045971
27,NOODLES,NOODLES,393,-393,393,0,-1.000000,1.000000,-0.995160,0.004840
28,PORK,SHRIMP,387,-294,294,93,-0.759690,0.759690,-0.757137,0.042437
29,SOY_SAUCE,SOY_SAUCE,136,-136,136,0,-1.000000,1.000000,-0.986264,0.013736
30,MUSHROOMS,MUSHROOMS,119,-119,119,0,-1.000000,1.000000,-0.984364,0.015636
31,GINGER,GINGER,34,-34,34,0,-1.000000,1.000000,-0.949241,0.050759
32,GREEN_ONION,GREEN_ONION,26,-26,26,0,-1.000000,1.000000,-0.935633,0.064367

In [12]:
# Save the discard ranking to a CSV file
output_filename = working_dir+'\\discarded_ingredient_ranking.csv'
pairs_df.to_csv(output_filename, index=False)
print(f"\nCombined ranking saved to '{output_filename}'")

Combined ranking saved to 'C:\Users\Joshua\Documents\GitSources\TabletopGames_StirFry18\SF18Experiments\10000RUNS\discarded_ingredient_ranking.csv'