In [1]:
import pandas as pd
import re
import numpy as np

In [2]:
working_dir = "C:\\Users\\Joshua\\Documents\\GitSources\\TabletopGames_StirFry18\\SF18Experiments\\10000RUNS"
action_chosen_dataframe = pd.read_csv(working_dir+'\\ACTION_CHOSEN.csv')

In [3]:
action_chosen_dataframe

,GameSeed,GameName,Round,Event,Tick,Turn,PlayerCount,GameID,CookList(Cooked with -),StateSpace(Size),...,GameScore(LeaderGap),GameScore(PlayerName-0),GameScore(Player-1),GameScore(Average),GameScore(Player-0),GameScore(Player-3),GameScore(Player-2),GameScore(PlayerName-1),GameScore(PlayerName-2),GameScore(PlayerName-3)
0,-1477572306,StirFry18,0,ACTION_CHOSEN,0,0,4,2,NaN,22,...,0.0,mcts,0.0,0.00,0.0,0.0,0.0,mcts,mcts,mcts
1,-1477572306,StirFry18,0,ACTION_CHOSEN,1,0,4,2,GREEN_ONION-NOODLES-PORK-,22,...,0.0,mcts,0.0,0.00,0.0,0.0,0.0,mcts,mcts,mcts
2,-1477572306,StirFry18,0,ACTION_CHOSEN,2,0,4,2,NaN,22,...,9.0,mcts,0.0,2.25,9.0,0.0,0.0,mcts,mcts,mcts
3,-1477572306,StirFry18,0,ACTION_CHOSEN,3,0,4,2,NaN,22,...,9.0,mcts,0.0,2.25,9.0,0.0,0.0,mcts,mcts,mcts
4,-1477572306,StirFry18,0,ACTION_CHOSEN,4,1,4,2,GINGER-MUSHROOMS-NOODLES-SOY_SAUCE-,22,...,9.0,mcts,0.0,2.25,9.0,0.0,0.0,mcts,mcts,mcts
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1341229,-1905857229,StirFry18,0,ACTION_CHOSEN,133,43,4,10001,NaN,22,...,1.0,mcts,44.0,42.00,45.0,35.0,44.0,mcts,mcts,mcts
1341230,-1905857229,StirFry18,0,ACTION_CHOSEN,134,44,4,10001,NaN,22,...,1.0,mcts,44.0,42.00,45.0,35.0,44.0,mcts,mcts,mcts
1341231,-1905857229,StirFry18,0,ACTION_CHOSEN,135,44,4,10001,GINGER-MUSHROOMS-NOODLES-SOY_SAUCE-,22,...,1.0,mcts,44.0,42.00,45.0,35.0,44.0,mcts,mcts,mcts
1341232,-1905857229,StirFry18,0,ACTION_CHOSEN,136,44,4,10001,NaN,22,...,7.0,mcts,44.0,43.50,51.0,35.0,44.0,mcts,mcts,mcts
1341233,-1905857229,StirFry18,0,ACTION_CHOSEN,137,44,4,10001,NaN,22,...,7.0,mcts,44.0,43.50,51.0,35.0,44.0,mcts,mcts,mcts

In [4]:
# Simplify the dataframe to keep only the specified columns
simplified_df = action_chosen_dataframe[[
    'GameSeed',  # Unique identifier for each game
    'Actions(Player-0)',  # Actions taken by player 0
    'Actions(Player-1)',  # Actions taken by player 1
    'Actions(Player-2)',  # Actions taken by player 2
    'Actions(Player-3)',  # Actions taken by player 3
    'GameScore(Player-0)',  # Score for player 0
    'GameScore(Player-1)',  # Score for player 1
    'GameScore(Player-2)',  # Score for player 2
    'GameScore(Player-3)',  # Score for player 3
    'CookList(Cooked with -)'  # Ingredients used in cooking actions
]]

# Display the first few rows of the simplified dataframe
simplified_df

,GameSeed,Actions(Player-0),Actions(Player-1),Actions(Player-2),Actions(Player-3),GameScore(Player-0),GameScore(Player-1),GameScore(Player-2),GameScore(Player-3),CookList(Cooked with -)
0,-1477572306,Discard Ingretients: 41 and 39,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN
1,-1477572306,"Cook with ids: 33, 37, 45,",NaN,NaN,NaN,0.0,0.0,0.0,0.0,GREEN_ONION-NOODLES-PORK-
2,-1477572306,pass,NaN,NaN,NaN,9.0,0.0,0.0,0.0,NaN
3,-1477572306,pass,NaN,NaN,NaN,9.0,0.0,0.0,0.0,NaN
4,-1477572306,NaN,"Cook with ids: 49, 35, 39, 44,",NaN,NaN,9.0,0.0,0.0,0.0,GINGER-MUSHROOMS-NOODLES-SOY_SAUCE-
...,...,...,...,...,...,...,...,...,...,...
1341229,-1905857229,NaN,NaN,NaN,pass,45.0,44.0,44.0,35.0,NaN
1341230,-1905857229,Discard Protein: 1711093,NaN,NaN,NaN,45.0,44.0,44.0,35.0,NaN
1341231,-1905857229,"Cook with ids: 1711099, 1711102, 1711106, 1711...",NaN,NaN,NaN,45.0,44.0,44.0,35.0,GINGER-MUSHROOMS-NOODLES-SOY_SAUCE-
1341232,-1905857229,pass,NaN,NaN,NaN,51.0,44.0,44.0,35.0,NaN
1341233,-1905857229,pass,NaN,NaN,NaN,51.0,44.0,44.0,35.0,NaN

In [5]:
# Create a new dataframe to find winners by game seed
winners_df = simplified_df.groupby('GameSeed').agg({
    'GameScore(Player-0)': 'max',
    'GameScore(Player-1)': 'max',
    'GameScore(Player-2)': 'max',
    'GameScore(Player-3)': 'max'
})

# Determine the winner for each game seed
def get_winner(row):
    for player in range(4):
        if row[f'GameScore(Player-{player})'] > 50:
            return player
    return -1  # No winner found

winners_df['Winner'] = winners_df.apply(get_winner, axis=1)

# Merge the winner information back to the original dataframe
simplified_df = simplified_df.merge(
    winners_df[['Winner']], 
    left_on='GameSeed', 
    right_index=True
)

# Display the first few rows of the updated dataframe
simplified_df

,GameSeed,Actions(Player-0),Actions(Player-1),Actions(Player-2),Actions(Player-3),GameScore(Player-0),GameScore(Player-1),GameScore(Player-2),GameScore(Player-3),CookList(Cooked with -),Winner
0,-1477572306,Discard Ingretients: 41 and 39,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,2
1,-1477572306,"Cook with ids: 33, 37, 45,",NaN,NaN,NaN,0.0,0.0,0.0,0.0,GREEN_ONION-NOODLES-PORK-,2
2,-1477572306,pass,NaN,NaN,NaN,9.0,0.0,0.0,0.0,NaN,2
3,-1477572306,pass,NaN,NaN,NaN,9.0,0.0,0.0,0.0,NaN,2
4,-1477572306,NaN,"Cook with ids: 49, 35, 39, 44,",NaN,NaN,9.0,0.0,0.0,0.0,GINGER-MUSHROOMS-NOODLES-SOY_SAUCE-,2
...,...,...,...,...,...,...,...,...,...,...,...
1341229,-1905857229,NaN,NaN,NaN,pass,45.0,44.0,44.0,35.0,NaN,0
1341230,-1905857229,Discard Protein: 1711093,NaN,NaN,NaN,45.0,44.0,44.0,35.0,NaN,0
1341231,-1905857229,"Cook with ids: 1711099, 1711102, 1711106, 1711...",NaN,NaN,NaN,45.0,44.0,44.0,35.0,GINGER-MUSHROOMS-NOODLES-SOY_SAUCE-,0
1341232,-1905857229,pass,NaN,NaN,NaN,51.0,44.0,44.0,35.0,NaN,0
1341233,-1905857229,pass,NaN,NaN,NaN,51.0,44.0,44.0,35.0,NaN,0

In [6]:
# Create a function to determine which player took the action in each row
def get_active_player(row):
    for player in range(4):
        action_col = f'Actions(Player-{player})'
        if pd.notna(row[action_col]) and row[action_col] != '':
            return player
    return -1  # No player found with an action

# Create a function to get the action name from the player's action column
def get_action_name(row):
    player = row['ActivePlayer']
    if player != -1:
        action_col = f'Actions(Player-{player})'
        return row[action_col]
    return ''

# Add the ActivePlayer column
simplified_df['ActivePlayer'] = simplified_df.apply(get_active_player, axis=1)

# Add the ActionTaken column
simplified_df['ActionTaken'] = simplified_df.apply(get_action_name, axis=1)

# Display the first few rows of the updated dataframe
simplified_df

,GameSeed,Actions(Player-0),Actions(Player-1),Actions(Player-2),Actions(Player-3),GameScore(Player-0),GameScore(Player-1),GameScore(Player-2),GameScore(Player-3),CookList(Cooked with -),Winner,ActivePlayer,ActionTaken
0,-1477572306,Discard Ingretients: 41 and 39,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,2,0,Discard Ingretients: 41 and 39
1,-1477572306,"Cook with ids: 33, 37, 45,",NaN,NaN,NaN,0.0,0.0,0.0,0.0,GREEN_ONION-NOODLES-PORK-,2,0,"Cook with ids: 33, 37, 45,"
2,-1477572306,pass,NaN,NaN,NaN,9.0,0.0,0.0,0.0,NaN,2,0,pass
3,-1477572306,pass,NaN,NaN,NaN,9.0,0.0,0.0,0.0,NaN,2,0,pass
4,-1477572306,NaN,"Cook with ids: 49, 35, 39, 44,",NaN,NaN,9.0,0.0,0.0,0.0,GINGER-MUSHROOMS-NOODLES-SOY_SAUCE-,2,1,"Cook with ids: 49, 35, 39, 44,"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1341229,-1905857229,NaN,NaN,NaN,pass,45.0,44.0,44.0,35.0,NaN,0,3,pass
1341230,-1905857229,Discard Protein: 1711093,NaN,NaN,NaN,45.0,44.0,44.0,35.0,NaN,0,0,Discard Protein: 1711093
1341231,-1905857229,"Cook with ids: 1711099, 1711102, 1711106, 1711...",NaN,NaN,NaN,45.0,44.0,44.0,35.0,GINGER-MUSHROOMS-NOODLES-SOY_SAUCE-,0,0,"Cook with ids: 1711099, 1711102, 1711106, 1711..."
1341232,-1905857229,pass,NaN,NaN,NaN,51.0,44.0,44.0,35.0,NaN,0,0,pass
1341233,-1905857229,pass,NaN,NaN,NaN,51.0,44.0,44.0,35.0,NaN,0,0,pass

In [7]:
# Get the final scores for each player in each game
final_scores = simplified_df.groupby('GameSeed').agg({
    'GameScore(Player-0)': 'max',
    'GameScore(Player-1)': 'max',
    'GameScore(Player-2)': 'max',
    'GameScore(Player-3)': 'max'
})

# Rename the columns to indicate these are final scores
final_scores = final_scores.rename(columns={
    'GameScore(Player-0)': 'FinalScore_Player0',
    'GameScore(Player-1)': 'FinalScore_Player1',
    'GameScore(Player-2)': 'FinalScore_Player2',
    'GameScore(Player-3)': 'FinalScore_Player3'
})

# Merge the final scores back to the original dataframe
simplified_df = simplified_df.merge(
    final_scores,
    left_on='GameSeed',
    right_index=True
)

# Display the first few rows of the updated dataframe
simplified_df

,GameSeed,Actions(Player-0),Actions(Player-1),Actions(Player-2),Actions(Player-3),GameScore(Player-0),GameScore(Player-1),GameScore(Player-2),GameScore(Player-3),CookList(Cooked with -),Winner,ActivePlayer,ActionTaken,FinalScore_Player0,FinalScore_Player1,FinalScore_Player2,FinalScore_Player3
0,-1477572306,Discard Ingretients: 41 and 39,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,2,0,Discard Ingretients: 41 and 39,25.0,40.0,54.0,37.0
1,-1477572306,"Cook with ids: 33, 37, 45,",NaN,NaN,NaN,0.0,0.0,0.0,0.0,GREEN_ONION-NOODLES-PORK-,2,0,"Cook with ids: 33, 37, 45,",25.0,40.0,54.0,37.0
2,-1477572306,pass,NaN,NaN,NaN,9.0,0.0,0.0,0.0,NaN,2,0,pass,25.0,40.0,54.0,37.0
3,-1477572306,pass,NaN,NaN,NaN,9.0,0.0,0.0,0.0,NaN,2,0,pass,25.0,40.0,54.0,37.0
4,-1477572306,NaN,"Cook with ids: 49, 35, 39, 44,",NaN,NaN,9.0,0.0,0.0,0.0,GINGER-MUSHROOMS-NOODLES-SOY_SAUCE-,2,1,"Cook with ids: 49, 35, 39, 44,",25.0,40.0,54.0,37.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1341229,-1905857229,NaN,NaN,NaN,pass,45.0,44.0,44.0,35.0,NaN,0,3,pass,51.0,44.0,44.0,35.0
1341230,-1905857229,Discard Protein: 1711093,NaN,NaN,NaN,45.0,44.0,44.0,35.0,NaN,0,0,Discard Protein: 1711093,51.0,44.0,44.0,35.0
1341231,-1905857229,"Cook with ids: 1711099, 1711102, 1711106, 1711...",NaN,NaN,NaN,45.0,44.0,44.0,35.0,GINGER-MUSHROOMS-NOODLES-SOY_SAUCE-,0,0,"Cook with ids: 1711099, 1711102, 1711106, 1711...",51.0,44.0,44.0,35.0
1341232,-1905857229,pass,NaN,NaN,NaN,51.0,44.0,44.0,35.0,NaN,0,0,pass,51.0,44.0,44.0,35.0
1341233,-1905857229,pass,NaN,NaN,NaN,51.0,44.0,44.0,35.0,NaN,0,0,pass,51.0,44.0,44.0,35.0

In [8]:
# Calculate the highest score for each game
simplified_df['HighestScore'] = simplified_df[['FinalScore_Player0', 'FinalScore_Player1', 
                                              'FinalScore_Player2', 'FinalScore_Player3']].max(axis=1)

# Calculate the score weight for each player
for player in range(4):
    simplified_df[f'ScoreWeight_Player{player}'] = simplified_df[f'FinalScore_Player{player}'] / simplified_df['HighestScore']

# Round the score weights to 3 decimal places for readability
for player in range(4):
    simplified_df[f'ScoreWeight_Player{player}'] = simplified_df[f'ScoreWeight_Player{player}'].round(3)

# Optionally, drop the temporary HighestScore column if not needed
simplified_df = simplified_df.drop(columns=['HighestScore'])

# Display the first few rows of the updated dataframe
simplified_df

,GameSeed,Actions(Player-0),Actions(Player-1),Actions(Player-2),Actions(Player-3),GameScore(Player-0),GameScore(Player-1),GameScore(Player-2),GameScore(Player-3),CookList(Cooked with -),...,ActivePlayer,ActionTaken,FinalScore_Player0,FinalScore_Player1,FinalScore_Player2,FinalScore_Player3,ScoreWeight_Player0,ScoreWeight_Player1,ScoreWeight_Player2,ScoreWeight_Player3
0,-1477572306,Discard Ingretients: 41 and 39,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,...,0,Discard Ingretients: 41 and 39,25.0,40.0,54.0,37.0,0.463,0.741,1.000,0.685
1,-1477572306,"Cook with ids: 33, 37, 45,",NaN,NaN,NaN,0.0,0.0,0.0,0.0,GREEN_ONION-NOODLES-PORK-,...,0,"Cook with ids: 33, 37, 45,",25.0,40.0,54.0,37.0,0.463,0.741,1.000,0.685
2,-1477572306,pass,NaN,NaN,NaN,9.0,0.0,0.0,0.0,NaN,...,0,pass,25.0,40.0,54.0,37.0,0.463,0.741,1.000,0.685
3,-1477572306,pass,NaN,NaN,NaN,9.0,0.0,0.0,0.0,NaN,...,0,pass,25.0,40.0,54.0,37.0,0.463,0.741,1.000,0.685
4,-1477572306,NaN,"Cook with ids: 49, 35, 39, 44,",NaN,NaN,9.0,0.0,0.0,0.0,GINGER-MUSHROOMS-NOODLES-SOY_SAUCE-,...,1,"Cook with ids: 49, 35, 39, 44,",25.0,40.0,54.0,37.0,0.463,0.741,1.000,0.685
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1341229,-1905857229,NaN,NaN,NaN,pass,45.0,44.0,44.0,35.0,NaN,...,3,pass,51.0,44.0,44.0,35.0,1.000,0.863,0.863,0.686
1341230,-1905857229,Discard Protein: 1711093,NaN,NaN,NaN,45.0,44.0,44.0,35.0,NaN,...,0,Discard Protein: 1711093,51.0,44.0,44.0,35.0,1.000,0.863,0.863,0.686
1341231,-1905857229,"Cook with ids: 1711099, 1711102, 1711106, 1711...",NaN,NaN,NaN,45.0,44.0,44.0,35.0,GINGER-MUSHROOMS-NOODLES-SOY_SAUCE-,...,0,"Cook with ids: 1711099, 1711102, 1711106, 1711...",51.0,44.0,44.0,35.0,1.000,0.863,0.863,0.686
1341232,-1905857229,pass,NaN,NaN,NaN,51.0,44.0,44.0,35.0,NaN,...,0,pass,51.0,44.0,44.0,35.0,1.000,0.863,0.863,0.686
1341233,-1905857229,pass,NaN,NaN,NaN,51.0,44.0,44.0,35.0,NaN,...,0,pass,51.0,44.0,44.0,35.0,1.000,0.863,0.863,0.686

In [9]:
# Complete combos dictionary based on the provided list
combos_dict = {
    # Shrimp combos
    "Shrimp-Ginger": ["Shrimp", "Ginger"],
    "Shrimp-Soy Sauce-Ginger": ["Shrimp", "Soy Sauce", "Ginger"],
    "Shrimp-Green Onion": ["Shrimp", "Green Onion"],
    
    # Pork combos
    "Pork-Mushrooms": ["Pork", "Mushrooms"],
    "Pork-Ginger": ["Pork", "Ginger"],
    
    # Chicken combos
    "Chicken-Green Onion": ["Chicken", "Green Onion"],
    "Chicken-Ginger-Green Onion": ["Chicken", "Ginger", "Green Onion"],
    "Chicken-Mushrooms": ["Chicken", "Mushrooms"],
    
    # Soy Sauce combos
    "Soy Sauce-Green Onion": ["Soy Sauce", "Green Onion"],
    "Soy Sauce-Ginger": ["Soy Sauce", "Ginger"]
}

def identify_combos_and_individuals(cook_list):
    if pd.isna(cook_list) or cook_list == "":
        return [], []
    
    # Split the ingredients and standardize format
    ingredients = [ing.strip().upper() for ing in cook_list.split("-")]
    ingredients = [ing for ing in ingredients if ing]  # Remove empty strings
    
    # Create a standardized version of ingredients for matching (replace underscores with spaces)
    std_ingredients = [ing.replace("_", " ") for ing in ingredients]
    
    found_combos = []
    
    # Check for all possible combos
    for combo_name, combo_ingredients in combos_dict.items():
        # Convert combo ingredients to uppercase for case-insensitive comparison
        combo_ingredients_upper = [ing.upper() for ing in combo_ingredients]
        
        # Check if all ingredients in this combo are present
        if all(ing in std_ingredients for ing in combo_ingredients_upper):
            found_combos.append(combo_name)
    
    # For individual ingredients, we need to check which ones weren't used in any combo
    used_in_combos = set()
    for combo_name in found_combos:
        for ing in combos_dict[combo_name]:
            used_in_combos.add(ing.upper())
    
    # Find individual ingredients
    individual_ingredients = [ing for ing in ingredients if ing.replace("_", " ") not in used_in_combos]
    
    return found_combos, individual_ingredients

# Apply the function to create new columns
simplified_df[['Combos', 'Individual_Ingredients']] = simplified_df.apply(
    lambda row: pd.Series(identify_combos_and_individuals(row['CookList(Cooked with -)'])), 
    axis=1
)

# Display the first few rows to verify
simplified_df[['CookList(Cooked with -)', 'Combos', 'Individual_Ingredients']]

,CookList(Cooked with -),Combos,Individual_Ingredients
0,NaN,[],[]
1,GREEN_ONION-NOODLES-PORK-,[],"[GREEN_ONION, NOODLES, PORK]"
2,NaN,[],[]
3,NaN,[],[]
4,GINGER-MUSHROOMS-NOODLES-SOY_SAUCE-,[Soy Sauce-Ginger],"[MUSHROOMS, NOODLES]"
...,...,...,...
1341229,NaN,[],[]
1341230,NaN,[],[]
1341231,GINGER-MUSHROOMS-NOODLES-SOY_SAUCE-,[Soy Sauce-Ginger],"[MUSHROOMS, NOODLES]"
1341232,NaN,[],[]
1341233,NaN,[],[]

In [27]:
import pandas as pd
import numpy as np
import scipy.stats as stats

# Create dictionaries to track scores for statistical analysis
combo_scores = {}
ingredient_scores = {}
combo_counts = {}
ingredient_counts = {}

# Process each row in the dataframe
for _, row in simplified_df.iterrows():
    # Skip if no cook action or missing data
    if pd.isna(row['CookList(Cooked with -)']) or row['CookList(Cooked with -)'] == "":
        continue
    
    # Get the active player who performed the cook action
    active_player = row['ActivePlayer']
    
    # Get the score weight for the active player
    score_weight_col = f'ScoreWeight_Player{active_player}'
    if score_weight_col not in row or pd.isna(row[score_weight_col]):
        continue
    
    score_weight = row[score_weight_col]
    
    # Process combos
    for combo in row['Combos']:
        if combo not in combo_scores:
            combo_scores[combo] = []
            combo_counts[combo] = 0
        combo_scores[combo].append(score_weight)
        combo_counts[combo] += 1
    
    # Process individual ingredients
    for ingredient in row['Individual_Ingredients']:
        if ingredient not in ingredient_scores:
            ingredient_scores[ingredient] = []
            ingredient_counts[ingredient] = 0
        ingredient_scores[ingredient].append(score_weight)
        ingredient_counts[ingredient] += 1

# Calculate statistics
combo_stats = {}
for combo, scores in combo_scores.items():
    if len(scores) > 1:  # Need at least 2 samples for std error
        mean = np.mean(scores)
        std_error = stats.sem(scores)
        combo_stats[combo] = {
            'Mean': mean,
            'StdError': std_error,
            'Count': len(scores),
            'CI_Lower': mean - 1.96 * std_error,  # 95% confidence interval
            'CI_Upper': mean + 1.96 * std_error
        }
    elif len(scores) == 1:  # Only one sample, can't calculate std error
        mean = scores[0]
        combo_stats[combo] = {
            'Mean': mean,
            'StdError': None,
            'Count': 1,
            'CI_Lower': None,
            'CI_Upper': None
        }

ingredient_stats = {}
for ing, scores in ingredient_scores.items():
    if len(scores) > 1:  # Need at least 2 samples for std error
        mean = np.mean(scores)
        std_error = stats.sem(scores)
        ingredient_stats[ing] = {
            'Mean': mean,
            'StdError': std_error,
            'Count': len(scores),
            'CI_Lower': mean - 1.96 * std_error,  # 95% confidence interval
            'CI_Upper': mean + 1.96 * std_error
        }
    elif len(scores) == 1:  # Only one sample, can't calculate std error
        mean = scores[0]
        ingredient_stats[ing] = {
            'Mean': mean,
            'StdError': None,
            'Count': 1,
            'CI_Lower': None,
            'CI_Upper': None
        }

# Create DataFrames for better visualization
combo_df = pd.DataFrame.from_dict(combo_stats, orient='index')
combo_df.reset_index(inplace=True)
combo_df.rename(columns={'index': 'Combo'}, inplace=True)
combo_df = combo_df.sort_values('Mean', ascending=False)

ingredient_df = pd.DataFrame.from_dict(ingredient_stats, orient='index')
ingredient_df.reset_index(inplace=True)
ingredient_df.rename(columns={'index': 'Ingredient'}, inplace=True)
ingredient_df = ingredient_df.sort_values('Mean', ascending=False)

# Display the results
print("Combo Average Score Weights with Error Margins:")
print(combo_df)
print("\nIndividual Ingredient Average Score Weights with Error Margins:")
print(ingredient_df)

Combo Average Score Weights with Error Margins:
                        Combo      Mean  StdError  Count  CI_Lower  CI_Upper
3          Shrimp-Green Onion  0.842229  0.001317  16161  0.839647  0.844811
9  Chicken-Ginger-Green Onion  0.837278  0.001871   8240  0.833611  0.840944
7                 Pork-Ginger  0.832809  0.001257  18714  0.830345  0.835273
2               Shrimp-Ginger  0.831008  0.001375  15547  0.828314  0.833702
6              Pork-Mushrooms  0.830970  0.001144  22838  0.828728  0.833213
8         Chicken-Green Onion  0.828479  0.001214  20626  0.826100  0.830858
4     Shrimp-Soy Sauce-Ginger  0.821413  0.002192   6287  0.817118  0.825709
5           Chicken-Mushrooms  0.818303  0.001153  23810  0.816044  0.820562
1       Soy Sauce-Green Onion  0.784571  0.000821  52519  0.782962  0.786179
0            Soy Sauce-Ginger  0.774521  0.000854  50205  0.772848  0.776194

Individual Ingredient Average Score Weights with Error Margins:
    Ingredient      Mean  StdError   Count  CI_Lower  CI_Upper
7       SHRIMP  0.817782  0.001637   11688  0.814573  0.820991
2         PORK  0.814846  0.001810    9932  0.811298  0.818395
4      CHICKEN  0.792116  0.002024    8569  0.788148  0.796083
1      NOODLES  0.781143  0.000436  189825  0.780289  0.781997
0  GREEN_ONION  0.770445  0.001128   28416  0.768233  0.772657
5    SOY_SAUCE  0.763396  0.001149   28403  0.761145  0.765647
3    MUSHROOMS  0.758514  0.000707   74505  0.757128  0.759899
6       GINGER  0.747024  0.001273   22975  0.744529  0.749520

In [31]:
# Create a combined DataFrame with a new column indicating the type (Combo or Ingredient)
# First, add a 'Type' column to each DataFrame
combo_df['Type'] = 'Combo'
ingredient_df['Type'] = 'Ingredient'

# Rename columns to be consistent
combo_df.rename(columns={'Combo': 'Item'}, inplace=True)
ingredient_df.rename(columns={'Ingredient': 'Item'}, inplace=True)

# Combine the DataFrames
combined_df = pd.concat([combo_df, ingredient_df], ignore_index=True)

# Sort by Mean score in descending order
combined_df = combined_df.sort_values('Mean', ascending=False)

print("\nTop 10 Items Overall:")
print(combined_df)

Combined Ranking (Combos and Ingredients):
                          Item      Mean  StdError   Count  CI_Lower  \
0           Shrimp-Green Onion  0.842229  0.001317   16161  0.839647
1   Chicken-Ginger-Green Onion  0.837278  0.001871    8240  0.833611
2                  Pork-Ginger  0.832809  0.001257   18714  0.830345
3                Shrimp-Ginger  0.831008  0.001375   15547  0.828314
4               Pork-Mushrooms  0.830970  0.001144   22838  0.828728
5          Chicken-Green Onion  0.828479  0.001214   20626  0.826100
6      Shrimp-Soy Sauce-Ginger  0.821413  0.002192    6287  0.817118
7            Chicken-Mushrooms  0.818303  0.001153   23810  0.816044
8                       SHRIMP  0.817782  0.001637   11688  0.814573
9                         PORK  0.814846  0.001810    9932  0.811298
10                     CHICKEN  0.792116  0.002024    8569  0.788148
11       Soy Sauce-Green Onion  0.784571  0.000821   52519  0.782962
12                     NOODLES  0.781143  0.000436  189825  0.780289
13            Soy Sauce-Ginger  0.774521  0.000854   50205  0.772848
14                 GREEN_ONION  0.770445  0.001128   28416  0.768233
15                   SOY_SAUCE  0.763396  0.001149   28403  0.761145
16                   MUSHROOMS  0.758514  0.000707   74505  0.757128
17                      GINGER  0.747024  0.001273   22975  0.744529

    CI_Upper        Type
0   0.844811       Combo
1   0.840944       Combo
2   0.835273       Combo
3   0.833702       Combo
4   0.833213       Combo
5   0.830858       Combo
6   0.825709       Combo
7   0.820562       Combo
8   0.820991  Ingredient
9   0.818395  Ingredient
10  0.796083  Ingredient
11  0.786179       Combo
12  0.781997  Ingredient
13  0.776194       Combo
14  0.772657  Ingredient
15  0.765647  Ingredient
16  0.759899  Ingredient
17  0.749520  Ingredient

In [33]:
# Save the combined ranking to a CSV file
output_filename = working_dir+'\\combined_ingredient_ranking.csv'
combined_df.to_csv(output_filename, index=False)
print(f"\nCombined ranking saved to '{output_filename}'")

Combined ranking saved to 'C:\Users\Joshua\Documents\GitSources\TabletopGames_StirFry18\SF18Experiments\10000RUNS\combined_ingredient_ranking.csv'